### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by jobberma** [bviebahn/react-native-star-rating-widget#70]
Hello,

Thanks for the plugin.

Can you please add RTL support ?

Thanks

**Comment by bviebahn** [comment]
Hi,
RTL should work, what are your problems with it?

**Comment by jobberma** [comment]
> Hi, RTL should work, what are your problems with it?

I do not find an attribute to reverse stars when layout is RTL

**Comment by bviebahn** [comment]
They should be automatically reversed. Can you check if `I18nManager.isRTL` is true?

**Comment by jobberma** [comment]
I do not use `I18nManager` to handle i18n, I check with `Localization.isRTL`

**Comment by bviebahn** [comment]
Where is `Localization.isRTL` coming from? I18nManager is the standard react-native module, if the phone is set to RTL, it should work with this package. If you are manually setting RTL using `Localization`, then I18nManager might not update, but you can force it there manually as well: `I18nManager.forceRTL(true)`.

**Comment by jobberma** [comment]
I am afraid it will break some styling but I will try it. It will be a good idea to let the user choose to activate RTL or not for your lib and not to automatically activate it.

**Comment by bviebahn** [comment]
Is your phone actually set up as RTL? react-native automatically adjusts your layout to RTL, so you shouldn't do your styling with RTL in mind. For example `flexDirection: 'row'` will automatically be right to left when RTL is set.

So rendering elements RTL actually comes out of the box with react-native, the only place where it is relevant for this package, is when handling touches: https://github.com/bviebahn/react-native-star-rating-widget/blob/master/src/StarRating.tsx#L68

That's why I think adding a `isRTL` prop would not really work, because if react-native (using i18nManager) doesn't render the app as RTL, there is no point in handling the touches in the package as RTL, because the component itself is still rendered LTR.

If you're expecting your phone to be in RTL, I think you should try to figure out why `i18nManager.isRTL` is not true.
